# Generated by Django 4.0.1 on 2022-01-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_social_twitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_twitter',
            field=models.URLField(blank=True, default='https://twitter.com/', help_text='https://twitter.com/YOUR USERNAME', null=True, verbose_name='Twitter'),
        ),
    ]
