# Generated by Django 4.0.1 on 2022-01-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_email_alter_profile_social_twitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='social_facebook',
            field=models.URLField(blank=True, default='https://facebook.com/', help_text='https://facebook.com/your.name.1234', null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_linkedin',
            field=models.URLField(blank=True, default='https://linkedin.com/in/', help_text='https://tr.linkedin.com/in/USERNAME-1234', null=True, verbose_name='Linkedin'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_youtube',
            field=models.URLField(blank=True, default='https://www.youtube.com/c/', help_text='https://www.youtube.com/c/YOUR CHANNEL NAME', null=True, verbose_name='youtube'),
        ),
    ]
