# Generated by Django 4.0.1 on 2022-01-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_social_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='social_facebook',
            field=models.URLField(blank=True, help_text='https://facebook.com/your.name.1234', null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_linkedin',
            field=models.URLField(blank=True, help_text='https://tr.linkedin.com/in/USERNAME-1234', null=True, verbose_name='Linkedin'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_twitter',
            field=models.URLField(blank=True, help_text='https://twitter.com/YOUR USERNAME', null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_youtube',
            field=models.URLField(blank=True, help_text='https://www.youtube.com/c/YOUR CHANNEL NAME', null=True, verbose_name='youtube'),
        ),
    ]
