# Generated by Django 4.0.1 on 2022-01-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_social_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, default='profiles/user-default.png', null=True, upload_to='profiles/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='short_intro',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Intro'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_facebook',
            field=models.URLField(blank=True, help_text='https://facebook.com/YOUR.NAME.1234', null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_github',
            field=models.URLField(blank=True, help_text='https://github.com/USERNAME', null=True, verbose_name='Github'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_twitter',
            field=models.URLField(blank=True, help_text='https://twitter.com/USERNAME', null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_youtube',
            field=models.URLField(blank=True, help_text='https://www.youtube.com/c/YOURCHANNELNAME', null=True, verbose_name='youtube'),
        ),
    ]
