# Generated by Django 4.0.1 on 2022-01-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_skill_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='social_website',
            field=models.URLField(blank=True, null=True, verbose_name='Personal Website'),
        ),
    ]
