# Generated by Django 4.0.1 on 2022-01-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_profile_social_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='social_youtube',
            field=models.URLField(blank=True, help_text='https://www.youtube.com/c/YOURCHANNELNAME', null=True, verbose_name='Youtube Channel'),
        ),
    ]
