# Generated by Django 4.0.1 on 2022-01-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='demo_link',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='Demo Link'),
        ),
        migrations.AlterField(
            model_name='project',
            name='featured_img',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='', verbose_name='Featured Image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='source_link',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='Source Link'),
        ),
    ]
